## Write proxy backend and db services
# use volume secret and environment


# Use this mysql image and this command for password
# image: mysql:8.0.19
#     command: '--default-authentication-plugin=mysql_native_password'